CREATE DATABASE [Dtb_RPG_Senai]

USE [Dtb_RPG_Senai]
-- REGRA DE NOMENCLATURA

---- CRIAÇÃO DAS TABELAS
CREATE TABLE JOGADORES
(
CODIGO_LOGIN INT IDENTITY  NOT NULL,
NICKNAME VARCHAR(100) NULL,
PASSWORD VARCHAR(50) NULL,
PRIMARY KEY (CODIGO_LOGIN)
)


CREATE TABLE JOGOS
(
CODIGO_JOGOS INT IDENTITY NOT NULL,
CODIGO_LOGIN INT NOT NULL,
NOME VARCHAR(50) NULL,
CLASSIFICACAO VARCHAR(20) NULL,
ATIVO BIT NULL,
PRIMARY KEY (CODIGO_JOGOS)
)


CREATE TABLE CAMPEONATO
(
CODIGO_CAMPEONATO INT IDENTITY  NOT NULL,
CODIGO_LOGIN INT NOT NULL,
CODIGO_JOGOS INT NOT NULL,
VITORIAS INT NULL,
DERROTAS INT NULL,
EMPATES INT NULL,
PRIMARY KEY (CODIGO_CAMPEONATO)
)



--- CRIAÇÃO DAS FOREIGN KEY
ALTER TABLE JOGOS
ADD CONSTRAINT FK_JOGADORES
FOREIGN KEY (CODIGO_LOGIN) REFERENCES JOGADORES (CODIGO_LOGIN);

ALTER TABLE CAMPEONATO
ADD CONSTRAINT FK_JOGADORES_CAMPEONATO
FOREIGN KEY (CODIGO_LOGIN) REFERENCES JOGADORES (CODIGO_LOGIN);


ALTER TABLE CAMPEONATO
ADD CONSTRAINT FK_JOGOS
FOREIGN KEY (CODIGO_JOGOS) REFERENCES JOGOS (CODIGO_JOGOS);


--- COMANDOS INSERTS

--- INSERINDO DADOS TABELAS JOGADORES
INSERT INTO JOGADORES (NICKNAME, PASSWORD)
VALUES
('VANDER', 'SENHA123');

INSERT INTO JOGADORES 
VALUES
('JOGADOR1', 'JG1SENHA123'),
('JOGADOR2', 'JG2ENHA123'),
('JOGADOR3', 'JG3SENHA123');


--- INSERINDO DADOS TABELAS JOGOS
INSERT INTO JOGOS ( CODIGO_LOGIN, NOME, CLASSIFICACAO, ATIVO)
VALUES
(1,'JOGO DE RPG', 'LIVRE', '1')

INSERT INTO JOGOS 
VALUES
(1,'JOGO DE RPG2', '18', '1')



INSERT INTO JOGOS ( CODIGO_LOGIN, NOME, CLASSIFICACAO, ATIVO)
VALUES
(2,'JOGO DE RPG', 'LIVRE', '1')

--- INSERINDO DADOS TABELAS CAMPEONATO
INSERT INTO CAMPEONATO (CODIGO_LOGIN, CODIGO_JOGOS, VITORIAS, DERROTAS, EMPATES)
VALUES
(1,2, 17, 0, 2),
(2,5, 0, 4, 4),
(3,6, 2, 5, 2 ),
(4,7, 14, 0, 4  );

--- COMANDOS SELECT
SELECT * FROM JOGADORES
SELECT * FROM JOGOS
SELECT * FROM CAMPEONATO

SELECT B.NICKNAME, A.VITORIAS, A.DERROTAS, A.EMPATES
FROM CAMPEONATO A
INNER JOIN JOGADORES B ON A.CODIGO_LOGIN = B.CODIGO_LOGIN

--- COMANDOS DELETE

DELETE FROM CAMPEONATO WHERE CODIGO_CAMPEONATO = 1

---COMANDO UPDATE
UPDATE  CAMPEONATO 
SET VITORIAS = '18' 
WHERE CODIGO_CAMPEONATO = 1







